version: '3'

services:
  web:
    build: ./php/
    container_name: php_apache_container
    ports:
      - 80:80
    volumes:
      - ./feedback/:/var/www/html

    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=feedback_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8080:80
      environment:
        - PMA_ARBITRARY=1